#!/bin/bash

set -o xtrace
set -e

link_in_homedir=( vimrc zshrc hyper.js tmux.conf gitignore_global hammerspoon asdfrc iterm2 iterm2_shell_integration.zsh gitconfig )
link_in_config=( fish nvim alacritty )

symlink_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for i in "${link_in_homedir[@]}"
do
	ln -nsf "$symlink_dir/$i" "$HOME/.$i"
done

mkdir -p ~/.config
for i in "${link_in_config[@]}"
do
	ln -nsf "$symlink_dir/$i" "$HOME/.config/$i"
done

git config --global core.excludesfile ~/.gitignore_global 

echo "Installing vim plugins"
vim -es -u "$HOME/.vimrc" -i NONE -c "PlugInstall" -c "qa"

if [ "$CODESPACES" = true ]; then
	echo "Running codespaces setup"
  sudo chsh -s /usr/bin/zsh
  sudo apt install -y exa
fi
