#!/bin/bash

set -o xtrace
set -e

link_in_homedir=( vimrc zshrc hyper.js tmux.conf gitignore_global hammerspoon asdfrc )
link_in_config=( fish nvim alacritty )

symlink_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for i in "${link_in_homedir[@]}"
do
	ln -nsf "$symlink_dir/$i" "$HOME/.$i"
done

mkdir -p ~/.config
for i in "${link_in_config[@]}"
do
	ln -nsf "$symlink_dir/$i" "$HOME/.config/$i"
done

git config --global core.excludesfile ~/.gitignore_global 
